//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRoute
    {
        public int Id { get; set; }
        public string FromIATA { get; set; }
        public string DestinationIATA { get; set; }
        public string AirlineOwner { get; set; }
        public string AirlineOperator { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airline Airline1 { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
    }
}
